services:
   
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: sso-kit-demo-keycloak
    hostname: sso-kit-demo-keycloak
    ports:
      - "8081:8080"
      - "8787:8787"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: 
    volumes:
      - ./docker/keycloak_data:/opt/keycloak/data
    command:
      - start-dev