services:
  app:
    #image: eclipse-temurin:17-jdk
    build: .
    user: ubuntu
    volumes:
      #- .:/workspace
      - .:/workspace:cached #Potential perf improvement but host changes are not syncronous
      - ${HOME}/.vaadin:/dot-vaadin:ro # to pass configs etc.. 
      # (Optional) Mount the Docker socket if you need to run docker commands inside the container:
      - /var/run/docker.sock:/var/run/docker.sock
    #command: bash
    #command: sleep infinity
        # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    # This is the primary container where you'll do your development work.

  