services:
   
  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: sso-kit-demo-keycloak
    hostname: sso-kit-demo-keycloak
    ports:
      - "8081:8080"
      - "8787:8787"
      - "9000:9000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      IMPORT_FILES_LOCATIONS: /opt/keycloak/data/import
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: 
    volumes:
      - ./keycloak_import:/opt/keycloak/data/import
    command:
      - start-dev
      - --health-enabled=true
      - --import-realm
      #- --verbose