version: "3.0"
services:
    keycloak:
      image: quay.io/keycloak/keycloak:19.0.3
      ports:
        - "8080:8080"
        - "8787:8787"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      command:
        - start-dev
