version: "3.0"
services:
    keycloak:
      #image: quay.io/keycloak/keycloak:19.0.3
      # Verified to work with version 20.0.3
      image: quay.io/keycloak/keycloak:20.0
      ports:
        - "8081:8080"
        - "8787:8787"
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      command:
        - start-dev
